spring:
  datasource:
    url: jdbc:mysql://localhost:3307/codebase
    username: dattv
    password: dattv@090399
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3600
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
